public class LinkedList{
       
    private Node head;
    private int numItems;
 
    public LinkedList(){
       this.head = null;
       this.numItems = 0;
    }
 
 
    public void add(int element){
 
    }      
 
    public void add(int index, int element){
 
    }
 
    public int get(int index){
 
    }
 
    public int remove(int index){
 
    }
 
    public int size(){
 
    }
 
    public boolean isEmpty(){
 
    }
 
 }
 
 